volumes:
  postgres: {}
  django_media: {}
  django_static: {}

services:
  postgres:
    container_name: postgres
    image: postgres:14.5-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: always

  backend:
    container_name: backend
    build: ./backend/
    entrypoint: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn gaggamagga.wsgi --workers=5 -b 0.0.0.0:8000"
    volumes:
      - ./backend/django/:/app/
      - /etc/localtime:/etc/localtime:ro
      - django_media:/app/media/
      - django_static:/app/static/
    environment:
      - DEBUG
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
    depends_on:
      - postgres
    restart: always
    
  daphne:
    container_name: daphne
    build: ./backend/
    command: daphne -b 0.0.0.0 -p 8080 gaggamagga.asgi:application
    volumes:
      - ./backend/django/:/app/
    environment:
      - DEBUG
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
    depends_on:
      - backend
      - postgres
    restart: always

  redis:
    image: redis:alpine
    restart: always
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-alpine
    ports:
      - "5672:5672"
    depends_on:
      - backend

  celery_work:
    container_name: celery_worker
    build: ./backend
    command: celery -A gaggamagga worker --concurrency=3 -l info
    volumes:
      - ./backend/django/:/app/
    environment:
      - DEBUG
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
    depends_on:
      - rabbitmq

  nginx:
    container_name: nginx
    image: nginx:1.23.2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/:/etc/ssl_test/
      - django_media:/media/
      - django_static:/static/
    depends_on:
      - daphne
    restart: always
